# Generated by Django 5.1.7 on 2025-05-07 15:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('role', models.CharField(choices=[('turnboy', 'Turnboy'), ('loader', 'Loader')], db_index=True, default='turnboy', max_length=20)),
                ('is_loader', models.BooleanField(default=False, help_text='Check if this person can also work as a loader')),
                ('date_joined', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.CharField(blank=True, max_length=100, null=True)),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(blank=True, choices=[('truck', 'Truck'), ('van', 'Van'), ('bus', 'Bus'), ('other', 'Other')], max_length=50)),
                ('capacity', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('delivery_note_image', models.ImageField(blank=True, null=True, upload_to='delivery_notes/')),
                ('turnboy_payment_rate', models.DecimalField(decimal_places=2, default=200.0, help_text='Base payment rate for turnboys for this delivery; can be adjusted based on distance', max_digits=10)),
                ('destination', models.CharField(max_length=100)),
                ('items_carried', models.TextField()),
                ('loading_amount', models.DecimalField(decimal_places=2, help_text='Total amount paid for loading', max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('in_progress', 'In Progress')], default='completed', max_length=20)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vehicle')),
            ],
            options={
                'verbose_name_plural': 'Deliveries',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PayrollManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_pay', models.DecimalField(decimal_places=2, default=0, help_text="Payment for the staff's primary role (turnboy, etc.)", max_digits=10)),
                ('loader_pay', models.DecimalField(decimal_places=2, default=0, help_text='Payment for loading activities if the staff helped with loading', max_digits=10)),
                ('total_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.delivery')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.staff')),
            ],
            options={
                'unique_together': {('staff', 'delivery')},
            },
        ),
        migrations.CreateModel(
            name='PaymentPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('role_payment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('loader_payment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.staff')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='period_end_gte_period_start')],
            },
        ),
        migrations.CreateModel(
            name='MonthlyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('role_payment', models.DecimalField(decimal_places=2, default=0, help_text="Payment for the staff's primary role (driver, turnboy, etc.)", max_digits=10)),
                ('loader_payment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.staff')),
            ],
            options={
                'unique_together': {('staff', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='StaffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('turnboy', 'Turnboy'), ('loader', 'Loader')], max_length=20)),
                ('helped_loading', models.BooleanField(default=False, help_text='Set to True if this staff member helped with loading')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.delivery')),
                ('staff', models.ForeignKey(limit_choices_to={'role__in': ['turnboy', 'loader']}, on_delete=django.db.models.deletion.CASCADE, to='app.staff')),
            ],
            options={
                'unique_together': {('delivery', 'staff', 'role')},
            },
        ),
    ]
