# Generated by Django 5.1.7 on 2025-04-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='status',
            field=models.BooleanField(default=True, help_text='Check if delivery was completed'),
        ),
    ]
