# Generated by Django 5.1.7 on 2025-04-11 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollmanager',
            name='role_pay',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Payment for the staff's primary role (turnboy, etc.)", max_digits=10),
        ),
        migrations.AlterField(
            model_name='staffassignment',
            name='role',
            field=models.CharField(choices=[('turnboy', 'Turnboy'), ('loader', 'Loader')], max_length=20),
        ),
        migrations.AlterField(
            model_name='staffassignment',
            name='staff',
            field=models.ForeignKey(limit_choices_to={'role__in': ['turnboy', 'loader']}, on_delete=django.db.models.deletion.CASCADE, to='app.staff'),
        ),
        migrations.DeleteModel(
            name='LoaderAssignment',
        ),
    ]
