# Generated by Django 5.1.7 on 2025-06-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='is_loader',
            field=models.BooleanField(default=True, help_text='Check if this person can also work as a loader'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
