# Generated by Django 5.1.7 on 2025-04-05 13:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='turnboy_payment',
            field=models.DecimalField(decimal_places=2, default=200.0, help_text='Payment for the turnboy for this delivery', max_digits=10),
        ),
    ]
