# Generated by Django 5.1.7 on 2025-04-06 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delivery_time_delivery_turnboy_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_note_image',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_notes/'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('in_progress', 'In Progress')], default='pending', help_text='Status of the delivery', max_length=20),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='turnboy_payment',
            field=models.DecimalField(decimal_places=2, default=200.0, help_text='Payment for the turnboy for this delivery; can be adjusted based on distance', max_digits=10),
        ),
        migrations.AlterField(
            model_name='staff',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('driver', 'Driver'), ('turnboy', 'Turnboy'), ('loader', 'Loader')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('truck', 'Truck'), ('van', 'Van'), ('bus', 'Bus'), ('other', 'Other')], max_length=50),
        ),
        migrations.CreateModel(
            name='PayrollManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turnboy_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('loader_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.delivery')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.staff')),
            ],
            options={
                'unique_together': {('staff', 'delivery')},
            },
        ),
    ]
