# Generated by Django 5.1.7 on 2025-04-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delivery_delivery_note_image_alter_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='turnboy_loaded',
            field=models.BooleanField(default=False, help_text='Set to True if the turnboy also helped with loading'),
        ),
    ]
